apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fortigate-exporter.fullname" . }}
  labels:
    {{- include "fortigate-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fortigate-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fortigate-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: fortigate-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9182
              name: metrics

          envFrom:
          - secretRef:
              name: "{{ .Values.fortigate.configSecretName }}"
