apiVersion: v1
entries:
  fortigate-exporter:
  - apiVersion: v2
    appVersion: latest
    created: "2025-04-22T13:51:05.207345+07:00"
    description: A Helm chart for Prometheus Fortigate Exporter
    digest: 68e47e75bcd02afe91b0130b26a984fc2b93db4d45d3f1400a5f95c5ff83fa80
    home: https://github.com/gopaytech/fortigate_exporter
    name: fortigate-exporter
    type: application
    urls:
    - fortigate-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-22T13:51:05.206693+07:00"
