name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Download Go module dependencies
        run: go mod download

      - name: Build fortigate_exporter binary
        run: |
          mkdir -p .build/linux-amd64
          GOOS=linux GOARCH=amd64 go build -o .build/linux-amd64/fortigate_exporter .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare fortigate-key.yaml with secret
        run: |
          sed "s/FORTIGATE_API_TOKEN/${{ secrets.AL_MP_ID_S_GENERAL_FG_01_API_KEY }}/" fortigate-key.yaml.template > fortigate-key.yaml

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64
